---
title: "download-scenarios"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{download-scenarios}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(trisk.analysis)
library(dplyr)
```


# Download the data




Data will be downloaded from this endpoint:
```{r}
print(
paste0(trisk.analysis:::TRISK_DATA_INPUT_ENDPOINT, "/", trisk.analysis:::TRISK_DATA_S3_PREFIX)
)
```


Choose the folder where to download the data
```{r}
trisk_inputs_folder <- file.path(".", "trisk_inputs")
```

Download the data using the provided function
```{r}
download_success <- download_trisk_inputs(local_save_folder = trisk_inputs_folder)
print(download_success)
```

# Descriptive statistics

## Sectors covered by scenarios 


```{r}
if (download_success) {
  scenarios <- read.csv(file.path(trisk_inputs_folder, "scenarios.csv"))
  number_of_scenario_per_sector <- scenarios %>%
    distinct(scenario, sector, technology) %>%
    group_by(sector, technology) %>%
    summarise(n_scenarios = n())
}
```

```{r}
if (download_success) {
  knitr::kable(number_of_scenario_per_sector) %>%
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
    kableExtra::scroll_box(width = "100%", height = "400px")
}
```


```{r}
if (download_success) {
  available_parameters <- get_available_parameters(scenarios)
}
```